archlinux/PKGBUILD
src/CMakeLists.txt
src/networkdetails.cpp

feat: add archlinux build

---

dde-network-dialog/networkpanel.cpp

1、关闭网络后，无法收到activeConnectionChange信号
2、网络设备数量为1时，没有发出updateFinished信号
Log: 修复关闭网络后点击右下角的网络图标没有响应的问题
Bug: https://pms.uniontech.com/bug-view-151615.html
Influence: 网络面板
Change-Id: Icb40909681ec0554056ec9148eb447f5398e59a6

fix: 修复关闭网络后点击网络图标没有响应的问题

---

dde-network-dialog/localclient.cpp

Lock属性名称错误
Log: 修复网络面板位置异常和无法消失的问题
Bug: https://pms.uniontech.com/bug-view-151667.html
Bug: https://pms.uniontech.com/bug-view-151659.html
Influence: 网络面板
Change-Id: I1092ca5178994b06e2e094617ce915dd27f143ef

fix: 修复网络面板位置异常和无法消失的问题

---

dde-network-dialog/dockpopupwindow.cpp

部分机型有问题，需要回退代码
This reverts commit 94995bc2fb16e68ec0ef22ccefdc501b9a42cc7e.

Revert "fix: 设置网络列表窗口类型为Tool (#27)"

---

CMakeLists.txt
common-plugin/secretagent.cpp
common-plugin/secretagent.h
dcc-network-plugin/CMakeLists.txt
dcc-network-plugin/connectioneditpage.cpp
dcc-network-plugin/connectionwirelesseditpage.cpp
dcc-network-plugin/sections/ethernetsection.cpp
dcc-network-plugin/sections/secrethotspotsection.cpp
dcc-network-plugin/sections/secretwirelesssection.cpp
dde-network-dialog/CMakeLists.txt
dde-network-dialog/item/wirelessconnect.cpp
dock-network-plugin/CMakeLists.txt
dss-network-plugin/CMakeLists.txt
src/CMakeLists.txt
src/realize/networkmanagerprocesser.cpp
try-compile/networkmanagerqt.cc

arclinux编译
Log: arclinux编译问题
Influence: 编译
Task: https://pms.uniontech.com/task-view-181437.html
Change-Id: Ic9fe6fdf6db5d5a257d7f56499840e5a3a7365c1

chore: 处理arclinux编译问题

---

archlinux/PKGBUILD
dcc-network-plugin/CMakeLists.txt
dde-network-dialog/CMakeLists.txt
debian/dss-network-plugin.install
debian/libdde-network-core-dev.install
debian/libdde-network-core.install
dock-network-plugin/CMakeLists.txt
dss-network-plugin/CMakeLists.txt
src/CMakeLists.txt

Use GNUInstallDir to install
Log: Use GNUInstallDir

chore(GNUInstallDir): Use GNUInstallDir

---

src/ipconfilctchecker.cpp

精简一些网络日志,避免日志太多对分析bug带来干扰(同步的V23的一些修改)
Log:
Task: https://pms.uniontech.com/task-view-89814.html
Influence: 无功能性影响
Change-Id: Ia616845350f1f3f2b6ea188cc814d443fae0bbf2

chore: 精简网络日志

---

dcc-network-plugin/connectioneditpage.cpp

调整ui间距
Log: 无
Influence: ui间距调整
Bug: https://pms.uniontech.com/bug-view-155161.html
Change-Id: I6b729eee857fada3a771913daa722fad6d587c7d

fix: 调整ui间距

---

CMakeLists.txt
src/dde-network-core.pc.in

Log: fix version in pkg-config

fix: set version for pkg-config

---

dss-network-plugin/network.json

提高api版本以适配最新的dde-session-shell
Log:
Task: https://pms.uniontech.com/task-view-154325.html
Influence: 登录锁屏界面网络插件
Change-Id: I308ccad631efa880e1c1172b57037e3804213228

feat: 适配支持2.0.0

---

dcc-network-plugin/proxypage.cpp
dcc-network-plugin/proxypage.h
src/networkconst.h
src/proxycontroller.cpp
src/proxycontroller.h

网络系统代理添加用户密码验证配置项
Log: 网络系统代理添加用户密码验证配置项
Task: https://pms.uniontech.com/task-view-212885.html
Influence: 网络系统代理添加用户密码验证配置项

feat: 网络系统代理添加用户密码验证配置项

---

dcc-network-plugin/connectioneditpage.cpp
dcc-network-plugin/sections/generichotspotsection.cpp
dcc-network-plugin/sections/genericsection.cpp
dcc-network-plugin/sections/genericsection.h
dcc-network-plugin/sections/wirelesssection.cpp
dcc-network-plugin/sections/wirelesssection.h
dcc-network-plugin/settings/wirelesssettings.cpp

优化无线网络名称与SSID重复问题
Log: 优化无线网络名称与SSID重复问题
Task: https://pms.uniontech.com/task-view-212909.html
Influence: 优化无线网络名称与SSID重复问题

feat(network): 优化无线网络名称与SSID重复问题

---

common-plugin/networkdialog.cpp
common-plugin/networkdialog.h
common-plugin/networkdialog/item/netitem.cpp
common-plugin/networkdialog/item/wirelessconnect.cpp
common-plugin/networkdialog/item/wirelessconnect.h
common-plugin/networkdialog/networkpanel.cpp
common-plugin/networkdialog/networkpanel.h
common-plugin/networkpluginhelper.cpp
common-plugin/secretagent.cpp
common-plugin/secretagent.h
dock-example/CMakeLists.txt
dock-example/docktestwidget.cpp
dock-example/main.cpp

修复连接隐藏网络问题
Log: 修复连接隐藏网络问题
Bug: https://pms.uniontech.com/bug-view-174223.html
Influence: 网络面板-连接网络

fix: 修复连接隐藏网络问题

---

dcc-network-plugin/icons/actions/dcc_importvpn_32px.svg
dcc-network-plugin/icons/dcc-network-plugin.qrc
dcc-network-plugin/vpnpage.cpp

优化控制中心网络模块导入VPN功能图标
Log: 优化控制中心网络模块导入VPN功能图标
Task: https://pms.uniontech.com/task-view-212941.html
Influence: 优化控制中心网络模块导入VPN功能图标

feat: 优化控制中心网络模块导入VPN功能图标

---

dcc-network-plugin/connectionvpneditpage.cpp

导出VPN时提供默认文件名
Log: 导出VPN时提供默认文件名
Influence: VPN默认文件名
Task: https://pms.uniontech.com/task-view-212939.html
Change-Id: Ifc0cf24c08de31bf354bf8fe6b914ec42e024a59

feat: 导出VPN时提供默认文件名

---

dcc-network-plugin/sections/vpn/vpnsection.cpp

VPN支持域名网关
Log: VPN支持域名网关
Task: https://pms.uniontech.com/task-view-212887.html
Influence: vpn

feat: VPN支持域名网关

---

src/realize/networkinterprocesser.cpp

网络详情同步算法有问题，导致与后端不同步。
Log: 修复网络详情错误
Bug: https://pms.uniontech.com/bug-view-174677.html
Influence: 网络详情

fix: 网络详情与后端不同步

---

common-plugin/networkdialog.cpp

密码输入框、解锁按钮、切换验证类型的按钮没有将事件向上传递给顶层窗口，没有接收到鼠标点击事件。
网络弹窗不应该依赖登录界面的实现，遍历子类并注册时间过滤器，不论登录界面如何实现都是收到点击事件。缺点：遍历&注册耗时（100+ms）
Log:
Bug: https://pms.uniontech.com/bug-view-172001.html
Influence: 登录、锁屏网络弹窗
Change-Id: I967c24e7c9c9889e040931bd631f1d5e0feba390

fix: 登录界面点击密码框网络弹窗不隐藏

---

common-plugin/item/devicestatushandler.cpp
dcc-network-plugin/networkmodulewidget.cpp
src/ipconfilctchecker.cpp
src/ipconfilctchecker.h
src/networkdevicebase.cpp
src/networkdevicebase.h
src/realize/netinterface.cpp
src/realize/netinterface.h
src/realize/networkinterprocesser.cpp

修复IP冲突无效问题
Log: 修复IP冲突无效问题
Bug: https://pms.uniontech.com/bug-view-172091.html
Influence: 网络
Change-Id: I2cc9d562dfd6444b7d0520c0a528b8e0fbdb57a8

fix: 修复IP冲突无效问题

---

common-plugin/item/devicestatushandler.cpp
dcc-network-plugin/networkmodulewidget.cpp
src/ipconfilctchecker.cpp
src/ipconfilctchecker.h
src/networkdevicebase.cpp
src/networkdevicebase.h
src/realize/netinterface.cpp
src/realize/netinterface.h
src/realize/networkinterprocesser.cpp

修复IP冲突无效问题
Log: 修复IP冲突无效问题
Bug: https://pms.uniontech.com/bug-view-172091.html Influence: 网络
Change-Id: I2cc9d562dfd6444b7d0520c0a528b8e0fbdb57a8
Co-authored-by: liaohanqin <liaohanqin@uniontech.com>
Change-Id: Ibb08eb68195b21fdbb1219031e80242fc8ded492

fix: 修复IP冲突无效问题 (#114)

---

dde-network-dialog/networkpanel.cpp
dde-network-dialog/networkpanel.h

网络面板增加透明效果
Log: 修复网络面板背景为白色没有透明效果的问题
Bug: https://pms.uniontech.com/bug-view-175755.html
Influence: 网络面板增加透明效果

fix: 网络面板增加透明效果

---

src/realize/devicemanagerrealize.cpp

修复热点激活问题
Log: 修复热点激活问题
Bug: https://pms.uniontech.com/bug-view-179755.html
Influence: 无
Change-Id: I81c275375f58d770ff828862032f0fcc82108e94

fix: 修复热点激活问题

---

.reuse/dep5

fix license
Log:
Task: https://pms.uniontech.com/task-view-232863.html
Influence: 无
Change-Id: I881299db77a73e2d53bfccaaf57b7df63e7a58d5

fix: fix license

---

debian/changelog

update changelog to 1.0.78
Log: update changelog to 1.0.78
Change-Id: I80e23f17da0198ebf031355ab8416fc2bdac5831

chore: update changelog to 1.0.78

---

.tx/deepin.conf
debian/changelog

update changelog to 1.1.9
Log: update changelog to 1.1.9
Influence: 构建
Change-Id: Ie26041dce744cb40bc186c72b68158c57a73bfc8

chore: update changelog to 1.1.9

---

CMakeLists.txt
dss-network-plugin/network_module.h
src/realize/networkmanagerprocesser.cpp

bring back enable_deepin_nmqt option

bring back enable_deepin_nmqt option

---

CMakeLists.txt
dcc-network-plugin/CMakeLists.txt
debian/dcc-network-plugin.install
debian/libdde-network-core-dev.install
debian/libdde-network-core.install
debian/rules
src/CMakeLists.txt

chore: use sovername

---

debian/changelog

chore: bump version to 2.0.5

---

debian/changelog

Update changelog to 2.0.6
Log:

chore: Update changelog to 2.0.6

---

dss-network-plugin/network_module.cpp

IconButton maybe be release by other.
Issue: https://github.com/linuxdeepin/developer-center/issues/4151

fix: SessionShell crashed

---

common-plugin/networkdialog.cpp

Correct a typo in networkdialog.cpp

chore: correct a typo in networkdialog.cpp

---

dcc-network-plugin/window/networkinfomodule.cpp

Log: wrong fix for networkdetail

fix: wrong fix for networkdetail

---

debian/changelog

chore: bump version to 2.0.8

---

dock-hotspot-plugin/hotspotplugin.cpp

并且统一QuickPanel和dock图标的点击行为
Log: 插件初始化时连接信号

fix: connect signal when plugin initialization

---

dcc-network-plugin/window/dccnetworkmodule.cpp

Issue: Issue: linuxdeepin/developer-center#4615

fix: Add dcc-network-plugin's displayName

---

.reuse/dep5
.tx/config
.tx/deepin.conf
dcc-network-plugin/lupdate.sh
dock-hotspot-plugin/lupdate.sh
dss-network-plugin/lupdate.sh

chore: update translations

---

dock-hotspot-plugin/hotspotplugin.cpp

fix: update hotspot state failed when connection was removed

---

dock-hotspot-plugin/hotspotplugin.cpp
dock-hotspot-plugin/hotspotplugin.h

quick panel add Tooltip
Log: 修复当网卡被设备管理器禁用时状态不改变

fix: unchanged state when network adapter was disabled by device manager

---

common-plugin/networkdialog/item/wirelessconnect.cpp
common-plugin/plugin_global.h
common-plugin/utils.h
common-plugin/widgets/tipswidget.h
dcc-network-plugin/window/editpage/connectionwirelesseditpage.cpp
debian/dock-hotspot-plugin.install
debian/rules
dock-hotspot-plugin/CMakeLists.txt
dock-hotspot-plugin/hotspotplugin.cpp
dock-hotspot-plugin/translations/dock-hotspot-plugin_en_US.ts
dock-hotspot-plugin/translations/dock-hotspot-plugin_zh_CN.ts
dock-network-plugin/translations/dock-network-plugin_en_US.ts
src/realize/networkmanagerprocesser.cpp

- 调整源代码结构
- 激活USE_DEEPIN_NMQT宏并移除没用的宏分支
- 添加热点插件的翻译
Log:

fix some error and add translation

---

dock-hotspot-plugin/hotspotplugin.cpp

fix: Accidentally deactivated hotspot connection due to uncertain signal order

---

dock-example/docktestwidget.cpp

chore: dock-example can't work

---

debian/changelog

chore: Update changelog to 2.0.13

---

debian/changelog

chore: Update changelog to 2.0.14

---

common-plugin/networkdialog/networkpanel.cpp

Force update when refresh timeout.
Issue: https://github.com/linuxdeepin/developer-center/issues/5484

fix: Missing update when refresh stopped

---

debian/changelog

chore: Update changelog to 2.0.15

---

dcc-network-plugin/window/dslmodule.cpp
dcc-network-plugin/window/hotspotmodule.cpp
dcc-network-plugin/window/vpnmodule.cpp
dcc-network-plugin/window/wiredmodule.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/5714 Log:

fix: not set fixed size for extra

---

debian/changelog

Issue: https://github.com/linuxdeepin/developer-center/issues/5823

chore: release 2.0.16

---

src/realize/networkinterprocesser.cpp

issue: https://github.com/linuxdeepin/developer-center/issues/5829

fix: sync changes of ActiveConnectionInfo

---

archlinux/PKGBUILD
dcc-network-plugin/CMakeLists.txt

chore: use new target link of dde-control-center

---

dcc-network-plugin/window/editpage/connectionvpneditpage.cpp
dcc-network-plugin/window/editpage/connectionvpneditpage.h

do not create a dialog pointer
Issue: https://github.com/linuxdeepin/developer-center/issues/6312 Log:

fix: vpn dialog open for a long time

---

dcc-network-plugin/icons/dcc-network-plugin.qrc
dcc-network-plugin/icons/texts/dcc_vpn_import_20px.svg
dcc-network-plugin/window/vpnmodule.cpp

replace the icon of the button
Issue: https://github.com/linuxdeepin/developer-center/issues/6576

fix: The icon of importing proxy isnt clear enough

---

debian/dcc-network-plugin.triggers
debian/dock-network-plugin.triggers
debian/dss-network-plugin.triggers
debian/libdde-network-core-dev.triggers
debian/libdde-network-core.triggers

fix: do not to trigger ldconfig

---

dcc-network-plugin/window/sysproxymodule.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/6523 Log:

fix: set extra btn of sysproxymodule to save

---

CMakeLists.txt
debian/changelog

chore: bump version to 2.0.17

---

CMakeLists.txt
dcc-network-plugin/window/sysproxymodule.cpp
debian/changelog
dss-network-plugin/dockpopupwindow.cpp

chore: bump version to 2.0.18

---

debian/changelog

chore: bump version to 2.0.20

---

dcc-network-plugin/window/sysproxymodule.cpp
dcc-network-plugin/window/sysproxymodule.h

store the last method from the combobox and display  the last method next time
Issue: https://github.com/linuxdeepin/developer-center/issues/6460

fix: default method is alway manual

---

debian/changelog

release 2.0.22
Log: bump version to 2.0.22

chore: bump version to 2.0.22

---

dcc-network-plugin/window/dccnetworkmodule.cpp

chore: Shielding app proxy module

---

debian/changelog

chore: bump version to 2.0.23

---

dcc-network-plugin/window/sections/genericsection.cpp
dcc-network-plugin/window/sections/wirelesssection.cpp

Disable dTextEdit not textEdit.
Log: fix line edit not fully disabled
Issue: https://github.com/linuxdeepin/developer-center/issues/5749

fix: line edit not fully disabled

---

dss-network-plugin/network_module.cpp
dss-network-plugin/network_module.h
dss-network-plugin/translations/dss-network-plugin.ts
dss-network-plugin/translations/dss-network-plugin_en_US.ts
dss-network-plugin/translations/dss-network-plugin_zh_CN.ts

Add chinese translation for warn label.
Log: warning label is not translated

fix: warning label is not translated

---

debian/changelog

chore: bump version to 2.0.24

---

debian/changelog

chore: bump version to 2.0.25

---

dcc-network-plugin/translations/dcc-network-plugin.ts
dcc-network-plugin/translations/dcc-network-plugin_zh_CN.ts
dcc-network-plugin/window/sections/secrethotspotsection.cpp
dcc-network-plugin/window/sections/secretwirelesssection.cpp

use DLineEdit showAlertMessage interface instead of old
Issue: 
- https://github.com/linuxdeepin/developer-center/issues/8692 
- https://github.com/linuxdeepin/developer-center/issues/8695

fix: lineedit alert style error

---

debian/changelog

release 2.0.26
Log: bump version to 2.0.26

chore: bump version to 2.0.26

---

dcc-network-plugin/translations/dcc-network-plugin.ts
dcc-network-plugin/translations/dcc-network-plugin_zh_CN.ts
dcc-network-plugin/window/sections/ipvxsection.cpp

Update translation
Log: Update translation

chore: Update translation

---

debian/changelog

chore: bump version to 2.0.27

---

debian/changelog

chore: bump version to 2.0.28
release 2.0.28
Log: bump version to 2.0.28

chore: bump version to 2.0.28

---

dss-network-plugin/network_module.cpp
dss-network-plugin/network_module.h

Issues: linuxdeepin/developer-center#8983

fix(dss): input  is not hidden after closing the window

---

dcc-network-plugin/window/sysproxymodule.cpp
src/networkdbusproxy.h
src/proxycontroller.cpp

Responding to proxy change signals
Issue: https://github.com/linuxdeepin/developer-center/issues/9711

fix: Responding to proxy change signals

---

.reuse/dep5
debian/dss-network-plugin.install
dss-network-plugin/10-network-manager.pkla
dss-network-plugin/50-dss-network-plugin.rules
dss-network-plugin/CMakeLists.txt

pkla 已经废弃，使用 rules 控制权限
Issues: linuxdeepin/developer-center#9630

fix(dss): can't connect to new WiFi

---

debian/changelog

bump to version 2.0.30
Log: bump to version 2.0.30

chore: bump to version 2.0.30

---

dcc-network-plugin/window/sysproxymodule.cpp
dcc-network-plugin/window/sysproxymodule.h

Wild pointer causing crash
Issue: https://github.com/linuxdeepin/developer-center/issues/10118

fix: Modify system proxy crash issue

---

dss-network-plugin/network_module.cpp
dss-network-plugin/network_module.h

Creating a network should be done after installing the translation
Issue: https://github.com/linuxdeepin/developer-center/issues/10018

fix: Modify the issue of untranslated network name created for the first time

---

debian/changelog

bump to version 2.0.32
Log: bump to version 2.0.32

chore: bump to version 2.0.32

---

common-plugin/networkdialog/item/netitem.cpp
common-plugin/networkdialog/item/netitem.h
src/realize/devicemanagerrealize.cpp

Network panel translation not dynamically updated
Issue: https://github.com/linuxdeepin/developer-center/issues/10226

fix: Network panel translation not dynamically updated

---

debian/changelog

bump version to 2.0.33
Log: bump version to 2.0.33

chore: bump version to 2.0.33

---

dcc-network-plugin/window/sysproxymodule.cpp
debian/changelog

chore: Bump version to 2.0.34

---

debian/changelog

Bump version to 2.0.35
Log: version 2.0.35
Task: https://pms.uniontech.com/task-view-361719.html

chore: Bump version to 2.0.35

---

dcc-network/CMakeLists.txt
dcc-network/operation/dccnetwork.cpp
dcc-network/operation/dccnetwork.h
dcc-network/qml/NetFileChooseEdit.qml
dcc-network/qml/NetPasswordEdit.qml
dcc-network/qml/NetUtils.js
dcc-network/qml/PageDSLSettings.qml
dcc-network/qml/PageSettings.qml
dcc-network/qml/PageVPNSettings.qml
dcc-network/qml/PageWiredDevice.qml
dcc-network/qml/SectionDNS.qml
dcc-network/qml/SectionDevice.qml
dcc-network/qml/SectionGeneric.qml
dcc-network/qml/SectionIPv4.qml
dcc-network/qml/SectionIPv6.qml
dcc-network/qml/SectionPPP.qml
dcc-network/qml/SectionPPPOE.qml
dcc-network/qml/SectionSecret.qml
dcc-network/qml/SectionVPN.qml
net-view/operation/netmanager.cpp
net-view/operation/netmanager.h
net-view/operation/private/netmanagerthreadprivate.cpp
net-view/operation/private/netmanagerthreadprivate.h

Add network configuration error handling
Log:
Task: https://pms.uniontech.com/task-view-361719.html

feat: Add network configuration error handling

---

debian/changelog

release 2.0.36
Log: bump version to 2.0.36

chore: bump version to 2.0.36

---

debian/changelog

release 2.0.37
Log: bump version to 2.0.37

chore: bump version to 2.0.37

---

dcc-network/qml/PageWirelessDevice.qml
dcc-network/qml/SectionDNS.qml
dcc-network/qml/SectionDevice.qml
dcc-network/qml/SectionGeneric.qml
dcc-network/qml/SectionIPv4.qml
dcc-network/qml/SectionIPv6.qml
dcc-network/qml/SectionPPP.qml
dcc-network/qml/SectionPPPOE.qml
dcc-network/qml/SectionSecret.qml
dcc-network/qml/SectionVPN.qml
dcc-network/qml/SystemProxyConfigItem.qml
dcc-network/qml/networkMain.qml

Enterprise network cannot connect
pms: BUG-286771

fix: Enterprise network cannot connect

---

dcc-network/qml/PageAirplane.qml
dcc-network/qml/PageAppProxy.qml
dcc-network/qml/PageDSL.qml
dcc-network/qml/PageDetails.qml
dcc-network/qml/PageHotspot.qml
dcc-network/qml/PageSystemProxy.qml
dcc-network/qml/PageVPN.qml
dcc-network/qml/PageWiredDevice.qml
dcc-network/qml/PageWirelessDevice.qml

Add menu item description
pms: Task-361719

feat: Add menu item description

---

dcc-network/translations/network.ts
dcc-network/translations/network_az.ts
dcc-network/translations/network_bo.ts
dcc-network/translations/network_ca.ts
dcc-network/translations/network_es.ts
dcc-network/translations/network_fi.ts
dcc-network/translations/network_fr.ts
dcc-network/translations/network_hu.ts
dcc-network/translations/network_it.ts
dcc-network/translations/network_ja.ts
dcc-network/translations/network_ko.ts
dcc-network/translations/network_nb_NO.ts
dcc-network/translations/network_pl.ts
dcc-network/translations/network_pt_BR.ts
dcc-network/translations/network_ru.ts
dcc-network/translations/network_uk.ts
dcc-network/translations/network_zh_CN.ts
dcc-network/translations/network_zh_HK.ts
dcc-network/translations/network_zh_TW.ts

Update translation
pms: Task-361719

feat: Update translation

---

debian/changelog

release 2.0.39
Log: bump version to 2.0.39

chore: bump version to 2.0.39

---

dcc-network/qml/SectionDevice.qml
dcc-network/translations/network.ts
dcc-network/translations/network_az.ts
dcc-network/translations/network_bo.ts
dcc-network/translations/network_ca.ts
dcc-network/translations/network_es.ts
dcc-network/translations/network_fi.ts
dcc-network/translations/network_fr.ts
dcc-network/translations/network_hu.ts
dcc-network/translations/network_it.ts
dcc-network/translations/network_ja.ts
dcc-network/translations/network_ko.ts
dcc-network/translations/network_nb_NO.ts
dcc-network/translations/network_pl.ts
dcc-network/translations/network_pt_BR.ts
dcc-network/translations/network_ru.ts
dcc-network/translations/network_uk.ts
dcc-network/translations/network_zh_CN.ts
dcc-network/translations/network_zh_HK.ts
dcc-network/translations/network_zh_TW.ts
net-view/operation/private/netmanagerthreadprivate.cpp
net-view/operation/private/netmanagerthreadprivate.h

1.Import file extension processing error
2.SSID with mandatory prompt
pms: BUG-287099
pms: BUG-286953

fix: Failed to modify VPN import issue

---

dcc-network/qml/network.qml

Update weight
pms: TASK-361721

feat: Update weight

---

debian/changelog

release 2.0.40
Log: bump version to 2.0.40

chore: bump version to 2.0.40

---

net-view/operation/private/netmanagerthreadprivate.cpp

Wireless enterprise network did not obtain password correctly
Log:
pms: BUG-294961

fix: Wireless enterprise network did not obtain password correctly

---

debian/changelog

release 2.0.41
Log: bump version to 2.0.41

chore: bump version to 2.0.41

---

src/proxycontroller.cpp

The data of the network proxy is not saved correctly
pms: TASK-361719

fix: The data of the network proxy is not saved correctly

---

config/org.deepin.dde.network.json
net-view/operation/private/netmanagerthreadprivate.cpp
src/configsetting.cpp

1. Create a temporary connection to an unconnected wireless network
2. Modify the flight mode configuration to default display
pms: BUG-297861
pms: BUG-295501

fix: Create a temporary connection to an unconnected wireless network

---

debian/changelog

release 2.0.42
Log: bump version to 2.0.42

chore: bump version to 2.0.42

---

dcc-network/qml/PageHotspot.qml

Modify hotspot UI style
pms: BUG-297167

fix: Modify hotspot UI style

---

debian/changelog

release 2.0.43
Log: bump version to 2.0.43

chore: bump version to 2.0.43

---

network-service-plugin/system/networkinitialization.cpp
network-service-plugin/system/networkinitialization.h

When modifying the system for the first time, the network did not automatically create an issue
pms: BUG-290803

fix: network did not automatically create

---

debian/changelog

release 2.0.44
Log: bump version to 2.0.44

chore: bump version to 2.0.44

---

debian/changelog

chore: bump version to 2.0.45

---

src/impl/networkmanager/devicemanagerrealize.cpp
src/impl/networkmanager/vpncontrollernm.cpp
src/impl/serviceinter/networkinterprocesser.cpp
src/networkcontroller.cpp
src/networkinter.h
src/proxycontroller.cpp

fix: Pop up authentication dialog box

---

debian/changelog

chore: bump version to 2.0.46 update changelog

---

dcc-network/qml/PageAppProxy.qml

Modify searchable items
pms: BUG-305009

fit: Modify searchable items

---

debian/changelog

chore: bump version to 2.0.47 update changelog

---

dcc-network/translations/network_zh_CN.ts

Update translation
pms: BUG-300373

fix: Update translation

---

debian/control

Add Dependency
Log: Add Dependency

chore: Add Dependency

---

.reuse/dep5
dcc-network/qml/PageSystemProxy.qml

Modify the proxy switch associated variable
pms: BUG-306433

fix: Modify the proxy switch associated variable

---

dcc-network/qml/PageSystemProxy.qml
net-view/operation/netitem.cpp
net-view/operation/netitem.h
net-view/operation/netmanager.cpp
net-view/operation/private/netitemprivate.cpp
net-view/operation/private/netitemprivate.h
net-view/operation/private/netmanagerthreadprivate.cpp
net-view/operation/private/netmanagerthreadprivate.h
network-service-plugin/accountnetwork/session/accountnetwork/activeaccoutnetwork.cpp

Record the last proxy method
pms: BUG-307643

fix: Record the last proxy method
