linuxdeepin/dde-network-core

dcc-network-plugin/sections/vpn/vpnopenconnectsection.cpp
dcc-network-plugin/sections/vpn/vpnopenvpnsection.cpp
dcc-network-plugin/sections/vpn/vpnsection.cpp
dcc-network-plugin/sections/vpn/vpnstrongswansection.cpp
dcc-network-plugin/sections/vpn/vpnvpncsection.cpp

remove the ip only check for add vpn
Log: remove the ip only check for add vpn
Resolve https://github.com/linuxdeepin/developer-center/issues/3304

feat: remove the ip only check for add vpn

---

dde-network-dialog/dockpopupwindow.cpp

/build/dde-network-core-1.0.32.2/dde-network-dialog/dockpopupwindow.cpp:243:22: error: aggregate 'QPainterPath path' has incomplete type and cannot be defined
QPainterPath path;
^~~~

fix: 修复构建错误

---

dcc-network-plugin/connectioneditpage.cpp

没有向DBUS注册NMVariantMapMap数据类型，在调用接口时无法解析此类型类所，导致程序崩溃
Log: 修复点击编辑网络连接时控制中心崩溃问题
Task: https://pms.uniontech.com/task-view-175119.html
Influence: 正常编辑网络连接
Change-Id: I9b8f6e0ef4498b60f3d943b33ad4da23bcf3e648

fix: 初始化网络连接编辑界面时需要向DBUS注册NMVariantMapMap数据类型

---

common-plugin/secretagent.cpp
dcc-network-plugin/connectioneditpage.cpp
dcc-network-plugin/connectioneditpage.h
dcc-network-plugin/connectionpageitem.cpp
dcc-network-plugin/hotspotpage.cpp
dcc-network-plugin/pppoepage.cpp
dcc-network-plugin/pppoepage.h
dcc-network-plugin/vpnpage.cpp
dcc-network-plugin/vpnpage.h
dcc-network-plugin/wiredpage.cpp
dcc-network-plugin/wirelesspage.cpp

1.网络连接过程中，“正在连接”的图标、显示在设置图标“>”左侧；
2.连接过程中，点击“>”进入设置页面：最上方显示【正在连接】、【删除】按钮，最下方显示【取消】、【保存】按钮；
3.连接过程中，【正在连接】按钮置灰、不可点击，连接成功后，显示为【断开连接】按钮、可以点击；【删除】、【取消】、【保存】沿用现有逻辑；
4.有线/无线/DSL/VPN/热点，需要统一修改
5.正在编辑连接信息时，点击其他连接时切换编辑界面内容到当前连接
Log: 修复连接过程中无法修改网络信息的问题
Bug: https://pms.uniontech.com/bug-view-151009.html
Influence: 连接过程中允许编辑连接信息，切换连接时切换编辑界面内容
Change-Id: Id9ac9eabd003bc8952aba13d2a99184e53f4a541

fix: 正在连接时允许修改连接信息

---

dcc-network-plugin/sections/vpn/vpnadvopenvpnsection.cpp

从OpenVPN配置文件导入VPN时，如果该文件中有配置“comp-lzo”或“comp-lzo
adaptive”，导入后在图形界面中“使用LZO压缩”这一开关仍是关闭的状态。原因：代码中的判断条件是“comp-lzo”值为"yes"时才开启，未考虑值为“adaptive”的情况。
Log: 修复“使用LZO压缩”未识别“comp-lzo adaptive”的问题
Influence: 控制中心 - 网络 - VPN - VPN高级选项 - 使用LZO压缩

fix: 修复“使用LZO压缩”未识别“comp-lzo adaptive”的问题

---

dcc-network-plugin/sections/secrethotspotsection.cpp

根据/sys/hisys/wal/wifi_devices_info文件中Chip Type值判断WIFI是否支持WPA3个人版安全协议， 其中
1103不支持1105支持，若无此文件默认支持
Log: 修复PanguV不支持WPA3加密个人，热点安全允许设置成WPA3模式的问题
Bug: https://pms.uniontech.com/bug-view-151699.html
Influence: PanguV不支持WPA3加密个人
Change-Id: I5b8e1b086a53223111d84b006eca48c55c5776ab

fix: 根据文件内容判断WIFI是否支持WPA3个人版安全协议

---

common-plugin/networkdialog.cpp
common-plugin/networkdialog.h
dde-network-dialog/localclient.cpp
dock-network-plugin/networkplugin.cpp
dss-network-plugin/network_module.cpp

由于socket连接错误,导致网络面板状态和位置异常
Log: 修复网络面板位置异常和无法消失的问题
Bug: https://pms.uniontech.com/bug-view-151667.html
Bug: https://pms.uniontech.com/bug-view-151659.html
Influence: 网络面板
Change-Id: I10e889f670b368d42a79467b1e1ea6bbf26091be

fix: 修复网络面板位置异常和无法消失的问题

---

dde-network-dialog/dockpopupwindow.cpp

设置网络列表窗口类型为Tool,密码框自动获取焦点
Log: 修复登录/锁屏界面点击加密WIFI时光标不在密码框的问题
Bug: https://pms.uniontech.com/bug-view-153215.html
Bug: https://pms.uniontech.com/bug-view-149739.html
Influence: 登录锁屏界面连接加密WIFI时，密码框自动获取焦点

fix: 设置网络列表窗口类型为Tool

---

dde-network-dialog/dockpopupwindow.cpp
dde-network-dialog/dockpopupwindow.h
dock-network-plugin/networkplugin.cpp

锁屏界面层级改为最高，导致锁屏之后网络面板无法自动隐藏
Log: 修复打开网络面板后锁屏，网络面板无法隐藏的问题
Bug: https://pms.uniontech.com/bug-view-153771.html
Influence: 打开网络面板，然后锁屏
Change-Id: I1c559c79cbd548c619eb9615e6dd3dac06c6974a

fix: 修复打开网络面板后锁屏，网络面板没有自动隐藏的问题

---

dcc-network-plugin/dccnetworkmodule.cpp

应该使用飞行模式的wifi状态来判断是否禁用按钮。
Log: 修复F9无法禁用wifi网络问题
Bug: https://pms.uniontech.com/bug-view-153777.html
Influence: wifi-网络
Change-Id: I7f96e64fd12cf6326f2c00e533fd403d3d6de00d

fix: 修复F9无法禁用wifi网络问题

---

.gitignore
dde-network-dialog/dockpopupwindow.cpp

原因：社区版上popup属性弹窗大概率没有抓取到键盘，可能跟qt的版本或者时序有关。
解决方案：弹窗显示的时候主动抓取一下.
PS：在两个进程“取消”和“抓取”的间隙，快捷键是可以使用的，目前的方案只是降低了出现问题的概率；
要从根本上解决需要把网络弹窗合入到锁屏作为一个进程。
Log: 解决社区版锁屏界面可以使用alt+tag快捷键的问题
Bug: https://pms.uniontech.com/bug-view-147677.html
Influence: 锁屏可以使用alt+tag快捷键
Change-Id: I6068286e38b0d1327b67c3422eac9ee1fc07a491

fix: 社区版锁屏界面可以使用alt+tag快捷键

---

dcc-network-plugin/dccnetworkmodule.cpp
dcc-network-plugin/dccnetworkmodule.h

需要关联设备信号,刷新飞行模式
Log: 飞行模式热插拔显示和隐藏
Influence: 飞行模式
Task: https://pms.uniontech.com/bug-view-155145.html

fix: 热插拔无线网卡后飞行模式没有显示

---

src/realize/deviceinterrealize.cpp
src/wirelessdevice.cpp
src/wirelessdevice.h

调用的方法错误，换成DeactivateConnection就可以了
Log: 修复无线络断开后无法自动回连的问题
Influence: 任务栏--无线网络，断开后自动回连
Bug: https://pms.uniontech.com/bug-view-146233.html
Change-Id: Ieb2483854164c373c9b88d28f0b56c8623d98d78

fix: 修复无线络断开后无法自动回连的问题

---

dcc-network-plugin/sections/secret8021xsection.cpp

企业版和其他的安全选项存储的配置不一样，需要进行区分
Log: 修复密码选项保存失效的问题
Influence: 密码选项由存储所有用户密码更改成仅为该用户存储密码后,重新打开仍生效
Bug: https://pms.uniontech.com/bug-view-154531.html
Change-Id: Ie2eb244c34929f0afb3a79cdbedc2ba7c6c7c417

fix: 修复密码选项保存失效的问题

---

dde-network-dialog/thememanager.cpp

wayland环境下，透明度太低背景太过透明
Log:
Bug: https://pms.uniontech.com/bug-view-155259.html
Influence: 深色模式下网络面板背景色

fix: 修复网络面板深色模式下网络面板背景色和SSID在白底下看不清问题

---

common-plugin/networkpluginhelper.cpp
common-plugin/networkpluginhelper.h
dock-example/docktestwidget.cpp
dock-example/docktestwidget.h
src/realize/devicemanagerrealize.cpp
src/wirelessdevice.cpp
src/wirelessdevice.h

当隐藏网络是否加密状态发生变化的时候，让其来显示密码框
Log: 修复隐藏网络连接失败的问题
Influence: ARM平台且wayland下，连接隐藏网络
Bug: https://pms.uniontech.com/bug-view-155277.html

fix: 修复隐藏网络连接失败的问题

---

src/realize/devicemanagerrealize.cpp
src/realize/devicemanagerrealize.h

1.网络列表应确保激活的连接点在列表中
2.NeedAuth为连接中状态
Log:
Bug: https://pms.uniontech.com/bug-view-149937.html
Influence: 登录界面-网络

fix(dde-network-core): 修改登录界面网络面板没有显示正在连接的WiFi问题

---

CMakeLists.txt

Make use of CMAKE_EXE_LINKER_FLAGS
Log: Don't ignore linker flags specified by system

fix: don't ignore linker flags specified by system

---

src/proxycontroller.cpp

避免硬编码查找路径，提高可移植性。
是解决 https://github.com/linuxdeepin/developer-center/issues/3374 问题的一部分。
和 https://github.com/linuxdeepin/deepin-screen-recorder/pull/207 类似

chore: don't use hardcode path 

---

dock-network-plugin/networkplugin.cpp

任务栏隐藏后网络面板不隐藏，避免网络面板同步隐藏后不方便操作网络
Log: 任务栏隐藏后网络面板不隐藏
Bug: https://pms.uniontech.com/bug-view-156749.html
Influence: 任务栏隐藏后网络面板不隐藏

fix: 任务栏隐藏后网络面板不隐藏

---

common-plugin/networkpluginhelper.cpp
common-plugin/secretagent.cpp
common-plugin/secretagent.h
dss-network-plugin/network_module.cpp
dss-network-plugin/network_module.h

之前是通过获取本地网络库的连接来获取连接的UUID，但是在刚刚连接隐藏网络的时候，网络库还未收到后端连接变化的信息，因此修改成从NetworkManagerQt中获取连接的方式来获取uuid
Log: 优化连接隐藏网络逻辑
Influence: 打开控制中心，连接隐藏网络，输入密码，观察任务栏是否弹出网络框让输入密码
Bug: https://pms.uniontech.com/bug-view-158483.html

fix: 修复在控制中心连接隐藏网络后任务栏弹出输入密码的提示

---

common-plugin/secretagent.cpp
dss-network-plugin/network_module.cpp

原因：登陆界面发现当前网络是保存为当前用户的时候，则弹出网络列表让用户输入密码，用户点击其他区域后，就取消了连接的操作，导致进入桌面后无法自动连接这个网络 修改：在登陆界面不让自动连接保存为当前用户的网络，进入桌面后就会自动连接到这个网络
Log: 修改无线网络保存为当前用户后重启系统无法自动连接的问题
Influence: 在控制中心连接加密网络，选择为保存当前用户，重启后进入桌面观察是否自动连接
Bug: https://pms.uniontech.com/bug-view-158911.html

fix: 修复网络密码保存为当前用户重启后无法自动连接的问题

---

common-plugin/networkpluginhelper.cpp

注册NMVariantMapMap类型，防止类型未注册导致主程序异常退出
Log: 修复网络库类型未注册qDbus导致锁屏异常退出的问题
Bug: https://pms.uniontech.com/bug-view-159567.html
Influence: 锁屏界面正常显示
Change-Id: I196172d26c3815874cd883469bd5776b20fcfab0

fix: 网络库类型未注册qDbus导致锁屏异常退出

---

common-plugin/networkdialog.cpp
common-plugin/networkdialog.h

锁屏程序监听到隐藏网络需要密码输入弹窗，启动了网络面板。该网络面板一直在后台运行，任务栏判断为有一个网络面板弹出了，没显示tips单击不弹窗
Log: 修改任务栏连接隐藏网络，概率性再点击无网络面板弹窗问题
Bug: https://pms.uniontech.com/bug-view-160229.html
Influence: 任务栏-网络-网络面板连接隐藏网络，修改网络密码后触发密码输入弹窗

fix: 修改任务栏在触发连接隐藏网络密码输入弹窗后hover无tips显示问题

---

common-plugin/secretagent.cpp

当用户注消连接会触发secret agent cancel 行为，导致对话框进程变空指针。
Log:
Task: https://pms.uniontech.com/task-view-196123.html
Influence: 登陆网络认证
Change-Id: I5addc901fa1caf75bbbc09b9653cf4ead3c3084e

fix: 修复secret agent 崩溃问题

---

common-plugin/networkpluginhelper.cpp
common-plugin/networkpluginhelper.h
src/realize/deviceinterrealize.cpp
src/realize/deviceinterrealize.h

任务栏的连接状态从后端服务读取,改成从网络服务的DBus接口来读取,保证状态始终是正确的
Log: 修复任务栏状态显示错误的问题
Influence: 偶现在网络全部连接成功后,任务栏网络图标显示正在连接,观察这种情况是否存在
Bug: https://pms.uniontech.com/bug-view-150305.html

fix: 修复任务栏连接状态错误的问题

---

dde-network-dialog/thememanager.cpp

现象：锁屏界面wifi列表背景颜色和数据颜色均显示白色,看着不够清晰。
方案：调整透明度
Log: 调整锁屏界面wifi弹窗透明度
Bug: https://pms.uniontech.com/bug-view-159545.html
Influence: 网络弹窗
Change-Id: I8999738dde34c3b9c39f9bfeb4d4de729d9f32ec

fix: wifi列表背景颜色

---

src/netutils.cpp
src/netutils.h

too many log message, use logging category to
enable or disbale logging message.
e.g. in dde-dock network plugin
QT_LOGGING_RULES="dde.network.core.dev=true" dde-dock
Log: logging category
Influence: network logging message
Change-Id: Ia050d69a9751446ca948186af6412b88b2fa06f9

chore: add logging category

---

dcc-network-plugin/wiredpage.cpp

刷新网络连接状态时更新网线是否插入提示信息是否可见
Log: 修复插拔网线后有线网络界面不会立即刷新问题
Bug: https://pms.uniontech.com/bug-view-164591.html
Influence: 插拔网线后有线网络界面及时刷新

fix: 刷新网络连接状态时更新网线是否插入提示信息是否可见

---

dcc-network-plugin/connectioneditpage.cpp

按设计要求，删除操作的危险行为，不管活动色是什么，删除按钮文字改为用红色的
Log: 修复控制中心删除VPN时的提示框没有适配活动色的问题
Bug: https://pms.uniontech.com/bug-view-162941.html
Influence: 网络删除按钮字体颜色
Change-Id: I14979c519afa125dddc0e7c1959c8e614143085f

fix: 修复控制中心删除VPN时的提示框没有适配活动色的问题

---

dde-network-dialog/dockpopupwindow.cpp
dde-network-dialog/dockpopupwindow.h

onboard的坐标并未进行缩放，导致判断鼠标是否在onboard内时发生错误
Log: 修复缩放后无法使用虚拟键盘输入网络密码的问题
Bug: https://pms.uniontech.com/bug-view-165195.html
Influence: 缩放时使用虚拟键盘输入网络密码
Change-Id: Id3caf59b6e4f9dfa723d8aa25fc7f0675cce9a83

fix: 缩放后无法使用虚拟键盘输入网络密码

---

src/realize/devicemanagerrealize.cpp
src/realize/devicemanagerrealize.h
src/wirelessdevice.h

原来的指针对象用的是普通的指针维护，在删除的时候容易重复删除引起崩溃；改成智能指针来管理指针对象
Log: 修复登陆界面网络崩溃的问题
Influence: 笔记本在登陆节目合上，再打开，观察是否会出现黑屏
Bug: https://pms.uniontech.com/bug-view-154983.html (cherry picked from commit 723d0681ff99a9e7dfe88ccb3bdab52a17b53d81)

fix: 修复网络偶现崩溃

---

src/realize/deviceinterrealize.cpp
src/realize/deviceinterrealize.h

在网络状态更新的时候，调用父类的setDeviceStatus方法来设置网络状态
Log: 修复控制中心不现实当前网络连接状态的问题
Influence: 打开控制中心，观察左侧网卡的连接状态
Bug: https://pms.uniontech.com/bug-view-166645.html
Bug: https://pms.uniontech.com/bug-view-171061.html

fix: 修复控制中心网卡不显示当前网络的连接状态的问题

---

common-plugin/networkdialog/networkpanel.cpp

刷新图标资源名错误
Log: 修改网络刷新图标为空问题
Bug: https://pms.uniontech.com/bug-view-172931.html
Influence: 任务栏、锁屏-网络列表-网络刷新图标

fix: 修改网络刷新图标为空问题

---

common-plugin/networkdialog/item/netitem.cpp
common-plugin/networkdialog/item/wirelessconnect.cpp
common-plugin/networkdialog/item/wirelessconnect.h
common-plugin/networkdialog/networkpanel.cpp
common-plugin/networkdialog/networkpanel.h
dcc-network-plugin/sections/secretwirelesssection.cpp

nm 不会对隐藏热点的settings进行补全，需要下游自行决定，
wpa-psk 不设置认证为 open 可能导致无法连接热点。
Log: 修复部份网络无法连接隐藏热点的问题
Bug: https://pms.uniontech.com/bug-view-155771.html
Influence: wifi
Change-Id: I1e9922fdae5c1254c9868a6dccada5a92bc31fee

fix: 修复部份网络无法连接隐藏热点的问题

---

dde-network-dialog/networkpanel.cpp

需要延时一段时间再展开密码输入框，否则界面和列表还没有显示出来时，输入框无法获得焦点
Log: 修复控制中心连接点击加密wifi唤起任务栏的网络面板中对应SSID密码框中无光标的问题
Bug: https://pms.uniontech.com/bug-view-172773.html
Influence: 密码输入框显示光标

fix: 需要延时一段时间再展开密码输入框

---

dss-network-plugin/network_module.cpp

原因：dde-session-shell改了一个类名（因为拼写错误），网络插件会根据这个类名判断是否要注册事件过滤器， 没有注册就无法捕捉到点击事件，从而导致网络弹窗无法弹出
Log：修复网络弹窗无法弹出的问题
Bug：https://pms.uniontech.com/bug-view-173777.html Influence：登录锁屏界面网络弹窗
Change-Id: I564926b9e7d641daf4d7d4e31bcf254740e0c41f

fix: 登录锁屏界面不显示网络弹窗

---

dde-network-dialog/thememanager.cpp

当设置的主题类型为浅色模式时，使用白色的背景
Log: 修复任务栏无线网络密码输入框焦点显示异常的问题
Bug: https://pms.uniontech.com/bug-view-172113.html
Influence: 任务栏连接无线网络输入框焦点显示
Change-Id: I8e0f9dfcfa2b2e8e4496593e8a41941e49ebd197

fix: 任务栏无线网络密码输入框焦点显示异常

---

dde-network-dialog/networkpanel.cpp

网络弹框的开关状态，应该与飞行模式的wifiEnabled属性状态绑定
Log: 修复快捷键关闭wifi功能任务栏无线网络开关显示异常的问题
Influence: 任务栏无线网络开关正常显示
Bug: https://pms.uniontech.com/bug-view-149279.html
Change-Id: I6dda4daca99da2760470c028bed6c715549d44f5

fix: 快捷键关闭wifi功能任务栏无线网络开关显示异常

---

dcc-network-plugin/sections/wirelesssection.cpp

开启热点未设置ssid
Log: 修复个人热点无法开启问题
Bug: https://pms.uniontech.com/bug-view-174545.html
Influence: 控制中心-开启个人热点

fix: 修复个人热点无法开启问题

---

src/realize/networkinterprocesser.cpp

网络详情同步算法有问题，导致与后端不同步。
Log: 修复网络详情错误
Bug: https://pms.uniontech.com/bug-view-174677.html Influence: 网络详情
Co-authored-by: liaohanqin <liaohanqin@uniontech.com>

fix: 网络详情与后端不同步 (#107)

---

common-plugin/trayicon.cpp

网络变化时，刷新频率过高，优化为500ms里有刷新状态时，不刷新。
Log: 优化图标刷新
Bug: https://pms.uniontech.com/bug-view-171129.html
Influence: dock网络图标
Change-Id: Ibae1c46bdd1638567a5d8e459b2fa79ada6468b3

fix: 优化图标刷新

---

dcc-network-plugin/connectioneditpage.cpp

创建热点时名称不提供默认值由用户自行填写
Log: 创建热点时名称不提供默认值由用户自行填写
Bug: https://pms.uniontech.com/bug-view-175381.html
Influence: 创建热点时名称不提供默认值由用户自行填写

fix: 创建热点时名称不提供默认值由用户自行填写

---

common-plugin/trayicon.cpp

网络变化时，刷新频率过高，优化为500ms里有刷新状态时，不刷新。
Log: 优化图标刷新
Bug: https://pms.uniontech.com/bug-view-171129.html Influence: dock网络图标
Change-Id: Ibae1c46bdd1638567a5d8e459b2fa79ada6468b3
Co-authored-by: liaohanqin <liaohanqin@uniontech.com>

fix: 优化图标刷新 (#109)

---

common-plugin/networkdialog.cpp

要求输入密码时任务栏先响应界面显示再显示密码输入框
Log: 修复控制中心连接点击加密wifi唤起任务栏的网络面板中对应SSID密码框中无光标问题
Bug: https://pms.uniontech.com/bug-view-172773.html
Influence: 要求输入密码时密码框有焦点

fix: 要求输入密码时任务栏先响应界面显示再显示密码输入框

---

src/realize/devicemanagerrealize.cpp
src/realize/devicemanagerrealize.h

连接监听"com.deepin.system.Network"的"DeviceEnabled"属性改变信号,及时刷新网络列表界面
Log: 修复登录界面上关闭无线网络时网络列表不会及时清空的问题
Bug: https://pms.uniontech.com/bug-view-179753.html
Influence: 关闭网络时及时清空无线网络列表

fix: 连接监听"com.deepin.system.Network"的"DeviceEnabled"属性改变信号

---

config/org.deepin.dde.network.json
dcc-network-plugin/proxypage.cpp
dcc-network-plugin/proxypage.h

关闭系统代理后，代理类型设置为none,再次打开时无法区分最后设置的代理类型，再次打开代理时全部默认为手动。 添加dconfig配置记录最后一次设置的代理类型，再次打开代理时根据保存的数据设置默认界面
Log: 修复代理类型选择自动后关闭系统代理开关后打开，代理类型为手动的问题
Bug: https://pms.uniontech.com/bug-view-179801.html
Influence: 打开系统代理时自动切换到最后一次设置的代理类型

fix: 保存最后一次设置的代理类型

---

.gitignore
src/ipconfilctchecker.cpp
src/ipconfilctchecker.h

原因：检查ip冲突时使用了悬空指针
方案：使用QPointer并增加判空
Log:
Bug: https://pms.uniontech.com/bug-view-180831.html
Influence: 登录、锁屏界面待机休眠唤醒
Change-Id: Ifb0f6697fb11babc4bc7d46369f8df1b78512824

fix: 登录界面崩溃

---

dss-network-plugin/network_module.cpp

原因:访问了空指针
处理方案: 指针析构后从list中移除
Log:
Bug: https://pms.uniontech.com/bug-view-180475.html
Influence: 登录、锁屏点击网络图标
Change-Id: I4871cbbb442a3a9a3c9105d0ee9785297a954e0f

fix: 登录/锁屏点击网络图标崩溃

---

common-plugin/networkdialog/networkpanel.cpp

主动断开了网络导致无法自动回连
Log: 修复dock栏无法自动回连问题
Bug: https://pms.uniontech.com/bug-view-181203.html
Influence: 网络
Change-Id: I11450cfaa7e52b807a07198c461d6d8c7aa95a68

fix: 修复dock栏无法自动回连问题

---

dcc-network-plugin/window/wirelessmodule.cpp
dcc-network-plugin/window/wirelessmodule.h

When opening the page, if the wireless network is
turned on, then scan.
Fixes linuxdeepin/developer-center#3761

fix: Control Center not automatically scanning for APs

---

dock-network-plugin/quickpanel.cpp

当字体设置为20时文本显示不全
resolve: https://github.com/linuxdeepin/developer-center/issues/3574
Log: 修复网络插件在快捷面板上的不正常显示

fix: Fix incorrect display of network plugins in QuickPanel

---

common-plugin/networkpluginhelper.cpp
common-plugin/networkpluginhelper.h
dss-network-plugin/network_module.cpp
dss-network-plugin/network_module.h

Simply return a DIconButton in content interface. Delegate the display of it to dde-session-shell. This will decouple dde-session-shell and dss-network-plugin.

refactor: delegate popup to dde-session-shell

---

dcc-network-plugin/window/sections/wirelesssection.cpp
dcc-network-plugin/window/sections/wirelesssection.h
dcc-network-plugin/window/settings/abstractsettings.cpp
dcc-network-plugin/window/settings/hotspotsettings.cpp
dcc-network-plugin/window/settings/wirelesssettings.cpp

设置项里InterfaceName与对应的MAC地址不匹配
修改为InterfaceName在绑定MAC地址时同时设置，无线网卡改为只能绑定当前网卡MAC地址
It lossed when merge v23 in 5c8817ca4058c0c6cd9150be8842a2e02ae61cd5 
Log:
Issue: https://github.com/linuxdeepin/developer-center/issues/3947 
Bug: https://pms.uniontech.com/bug-view-148023.html Influence: 控制中心-网络-创建热点
Change-Id: If878cec66843ec9c5dd07382d6b5171f5771b8ce

fix(dcc-network-plugin): 修改在多块无线网卡绑定到其他设备MAC时无法开启热点问题

---

common-plugin/networkdialog/networkpanel.cpp

We should change the painter's brush temporarily.
Issue: https://github.com/linuxdeepin/developer-center/issues/4068

fix: Hightlight background for wireless panel

---

CMakeLists.txt

CMakeLists.txt的HOMEPAGE_URL值末尾多了一个字符9。
Log: 修改了CMakeLists.txt的HOMEPAGE_URL值

fix: CMakeLists.txt的HOMEPAGE_URL值错误

---

dcc-network-plugin/window/sysproxymodule.cpp

Problem: the line "proxy type" of the page "system proxy" doesn't have grey backgroundcolor like other lines.
Solution: I used addBackground() to make this line the same like others
Issue: #141 
Log:  add grey backgroundcolor to the line proxy type of page system proxy.

fix: add backgroundcolor to the line proxy type

---

dcc-network-plugin/window/sections/secrethotspotsection.cpp

新增个人热点的弹窗是3个并列的Widget，分别是genericSection、secretHotspotSection、wirelessSection
其中secretHotspotSection即为安全选项，这个Widget没有标题，修改后给secretHotspotSection一个标题，使得3个Widget格式一致，间隔也一致。
Issue: #141 
Log: 修复了新增个人热点的弹窗名称与安全之间的间隔过大的问题
修改前效果：
修改后效果：

fix: 修复了新增个人热点的弹窗名称与安全之间的间隔过大的问题

---

src/ipconfilctchecker.cpp
src/ipconfilctchecker.h
src/realize/networkinterprocesser.cpp

We release QObject by deleteLater instead of delete,
IpConfilctChecker is delete in NetworkInterProcesser, and it's thread is in main thread, but IpConfilctChecker object is moved to QThread, it causes QObject is delete in other thread.

fix: Crashed when exit running in debug qt

---

dcc-network-plugin/CMakeLists.txt
dcc-network-plugin/window/dccnetworkmodule.cpp
debian/dcc-network-plugin.install
example/main.cpp

QTranslater must be installed in main thread.
We don't load translate, and it's loaded by `dde-control-center`

fix: App crashed running in debug QT

---

dcc-network-plugin/CMakeLists.txt

Add ${DCC_INTERFACE_LIBRARIES} link for dcc-network-plugin
Log: Need link this library link to fix build on openSUSE

fix: Add a missing library link

---

src/realize/networkmanagerprocesser.cpp

IPConflictChecker should be deleted in the thread it was created. Do not use "delete", just use deleteLater to emit a signal that will be disposed in the thread created later.
Log: fix crash on exit when running in qt debug version

fix: crash on exit when running in qt debug ver

---

dcc-network-plugin/window/editpage/connectioneditpage.cpp

隐藏了滚动条，修复了无线网络、有线网络（添加网络配置）、DSL（创建PPPoE连接）、VPN（添加VPN）一共四个页面的内容区没有居中于弹窗的问题。
修复的具体内容：
内容区的布局设置了横向居中对齐，最终使得内容区实现了居中效果。
Issue: #141
Log: 修复了内容区没有居中于弹窗的问题
修改前页面:
修改后页面:

fix: 修复了内容区没有居中于弹窗的问题

---

dcc-network-plugin/window/sections/secrethotspotsection.cpp

In WPA3-Personal Transition Mode, We change `802-11-wireless-security.proto`
from {`wpa`, rsn} to {wpa}
In `network-manager` project `src/core/supplicant/nm-supplicant-config.c:908`.
`key_mgmt` will be added `SAE` if `pmf` isn't false, it will works in unsupport `SAE` networkcard.
We don't use `RSN` wireless-security proto for the Transition Mode.
TODO: How should we configure it in WPA3-Personal Transition Mode?
Issue: https://github.com/linuxdeepin/developer-center/issues/3732

fix: Hotspot can't be connected for Wpa/Wpa2

---

dcc-network-plugin/window/sections/secrethotspotsection.cpp

fix: disable wpa3 transition mode when using wpa-psk

---

dock-hotspot-plugin/hotspotplugin.cpp
dock-hotspot-plugin/quickpanel.cpp

fix: QuickPanel text is imcompleted when font set to 20

---

dock-hotspot-plugin/hotspotplugin.cpp

fix: Even if the hotspot does not exist its state should change

---

dss-network-plugin/network_module.cpp
dss-network-plugin/network_module.h

NetworkDBusProxy is invalid, we delay construct NetworkModule to
avoid NetworkManager service hasn't ready, e.g: dde-session-daemon.

fix: NetworkPanel'status unrefreshed for dss-network-plugin

---

dcc-network-plugin/window/sections/multiipvxsection.cpp

this widget set title itself, but not set margin as it base class do, so it cause margin issue
Log:

fix: setContentsMargins of multiipvxsection

---

dock-hotspot-plugin/CMakeLists.txt
dock-hotspot-plugin/hotspotplugin.cpp
dock-hotspot-plugin/hotspotplugin.h

Monitoring device changed from m_notifier to NetworkManager::notifier.
Removing item when foreach m_wirelessDevices, it causes app crashed.
Issue: https://github.com/linuxdeepin/developer-center/issues/5023

feat: Hide hotspot plugin when unsupport hotspot

---

src/realize/deviceinterrealize.cpp

`ActivateAccessPoint` will create a new connection if uuid is emtpy.
and it's uuis is fetched from `Connection`, and before we don't distinguish the connections of different wireless device.
Issue: https://github.com/linuxdeepin/developer-center/issues/5005

fix: Doesn't connect the same AP for two wireless device

---

dcc-network-plugin/window/controllitemsmodel.cpp
dcc-network-plugin/window/wirelessdevicemodel.cpp

Settings button is set invisible when connecting,
and DStyledItemDelegate can't support Qt::AlignRight for the action in DStyledItemDelegatePrivate::doActionsLayout
```
center_rect.setLeft(result_list.last().right() + spacing);
```
so we align it by AlignLeft.
Issue: https://github.com/linuxdeepin/developer-center/issues/5146

fix: Can't set connection when connecting

---

dcc-network-plugin/window/sections/vpn/vpnopenvpnsection.cpp

fix: OpenVPN网关校验等相关问题：
1、认证类型为“密码”时，当CA证书、用户名、密码均非空，而网关为空的情况下，点击保存按钮，网关校验结果会被覆盖为true 
2、未选择CA证书时，点击保存按钮，CA证书校验结果会被覆盖为true
3、网关栏校验仅允许纯ipv4地址通过，导致ipv6、域名、附带端口号、多个remote的情况下无法通过校验，影响使用。

fix: OpenVPN网关校验等相关问题

---

debian/control

fix: remove unused libdframeworkdbus-dev builddep from debian/control

---

common-plugin/networkdialog/item/netitem.cpp
common-plugin/networkdialog/networkpanel.cpp
common-plugin/utils.h
common-plugin/widgets/tipswidget.cpp
dock-network-plugin/networkplugin.cpp
dss-network-plugin/dockpopupwindow.h
dss-network-plugin/network_module.cpp
dss-network-plugin/notification/actionbutton.cpp
src/realize/netinterface.cpp
src/realize/networkinterprocesser.cpp
src/realize/networkmanagerprocesser.cpp

chore: deprecated handle

---

dcc-network-plugin/window/hotspotmodule.cpp

do not connect a connected item
add DCC_NET_AC_AUTO_ON(default not set) to auto turn on AC
Issue: https://github.com/linuxdeepin/developer-center/issues/6014

fix: click connected AC will reatart AC(#6014)

---

dcc-network-plugin/window/settings/abstractsettings.cpp
dcc-network-plugin/window/settings/abstractsettings.h
dcc-network-plugin/window/settings/dslpppoesettings.cpp
dcc-network-plugin/window/settings/dslpppoesettings.h
dcc-network-plugin/window/settings/hotspotsettings.cpp
dcc-network-plugin/window/settings/hotspotsettings.h
dcc-network-plugin/window/settings/vpn/vpnl2tpsettings.h
dcc-network-plugin/window/settings/vpn/vpnopenconnectsettings.h
dcc-network-plugin/window/settings/vpn/vpnopenvpnsettings.h
dcc-network-plugin/window/settings/vpn/vpnpptpsettings.h
dcc-network-plugin/window/settings/vpn/vpnsstpsettings.h
dcc-network-plugin/window/settings/vpn/vpnstrongswansettings.h
dcc-network-plugin/window/settings/vpn/vpnvpncsettings.h
dcc-network-plugin/window/settings/wiredsettings.cpp
dcc-network-plugin/window/settings/wiredsettings.h
dcc-network-plugin/window/settings/wirelesssettings.cpp
dcc-network-plugin/window/settings/wirelesssettings.h

* 若本来有 interface-name，不处理
* 若 setInterfaceName() 返回 true，且 devPath 不为空，则设置 interface-name
Issues: linuxdeepin/developer-center#5804

fix: interface-name is cleared after modifying the network profile

---

dss-network-plugin/network_module.cpp
dss-network-plugin/network_module.h

Available connections is always empty when device is not available.
Iterate connection list to find a matched connection instead.
Log: fix duplicate connection created in greeter
Issue: https://github.com/linuxdeepin/developer-center/issues/7465

fix: duplicate connection created in greeter 

---

src/realize/networkinterprocesser.cpp

QList's iterator is damaged when removed one item.

fix: wild pointer for networkDetails

---

dcc-network-plugin/window/wirelessdevicemodel.cpp

loadingIndicator is deleted after spinner action is deleted
Issue: https://github.com/linuxdeepin/developer-center/issues/5747

fix: loadingIndicator isn't deleted

---

common-plugin/networkpluginhelper.cpp
common-plugin/networkpluginhelper.h
dss-network-plugin/network_module.cpp
dss-network-plugin/network_module.h

When plugin state is Nocable, Disabled and Unknown(Usually means that NetworkManager is not running or there is no cable), the network panel list is empty in dde-session-shell and there is no warning message. Display a warning message.
Log: fix empty network panel when unavailable.
Issue: https://github.com/linuxdeepin/developer-center/issues/7208

fix: empty network panel when unavailable

---

common-plugin/networkdialog/item/netitem.cpp
common-plugin/networkdialog/networkpanel.cpp

Set the text color to white in lock
Issue: https://github.com/linuxdeepin/developer-center/issues/8505wq

fix: netItem textColor error and the selected button is not centered 

---

common-plugin/networkdialog/item/netitem.cpp

Issues: linuxdeepin/developer-center#8504

fix: secure icons in lock screen are too small

---

dcc-network-plugin/window/sections/vpn/vpnopenconnectsection.cpp
dcc-network-plugin/window/sections/vpn/vpnsection.cpp
dcc-network-plugin/window/sections/vpn/vpnstrongswansection.cpp
dcc-network-plugin/window/sections/vpn/vpnvpncsection.cpp

Remove verification of the gateway
If the user fills in the wrong gateway information, there will be a prompt indicating that they cannot connect
与产品沟通, 去掉对网关的校验, 与v20专业版和20.9保持一致, 若用户输入错误的网关, 会有连接失败的提示
Issue: https://github.com/linuxdeepin/developer-center/issues/9437

fix: VPN gateway cannot input ip:port

---

debian/changelog

* fix(dss): input  is not hidden after closing the window (linuxdeepin/developer-center#8983)

chore: bump version to 2.0.29

---

dcc-network-plugin/window/sysproxymodule.cpp

In the page function, sub items will be traversed, and modifying sub items will cause window confusion. Instead, synchronize data before calling the page function
Issue: https://github.com/linuxdeepin/developer-center/issues/9961

fix: Modify the interface to display multiple system proxy issues

---

dcc-network-plugin/window/sysproxymodule.cpp
dcc-network-plugin/window/sysproxymodule.h
debian/changelog

When configuring incorrectly, setting the proxy did not take effect, resulting in asynchronous network proxy status on the taskbar
Issue: https://github.com/linuxdeepin/developer-center/issues/9983

fix: Modifying configuration errors can also set proxy issues

---

dss-network-plugin/network_module.h

The onUserChanged function requires the Q_SLOTS identifier
Issue: https://github.com/linuxdeepin/developer-center/issues/10071

fix: Modify network plugin translation issues

---

src/realize/devicemanagerrealize.cpp

Deleting loop objects within the loop leads to a crash
Issue: https://github.com/linuxdeepin/developer-center/issues/10263

fix: Modify network plugin crash issue

---

dcc-network/qml/PageAirplane.qml
dcc-network/qml/PageHotspot.qml
dcc-network/qml/PageWirelessDevice.qml
dcc-network/qml/main.qml
net-view/operation/netmanager.cpp
net-view/operation/private/nethotspotcontroller.cpp
net-view/operation/private/nethotspotcontroller.h
net-view/operation/private/netmanagerthreadprivate.cpp
net-view/operation/private/netmanagerthreadprivate.h

Handling hidden logic on web pages
Log:
Bug: https://pms.uniontech.com/bug-view-282419.html

fix: Handling hidden logic on web pages

---

dcc-network/qml/PageDSLSettings.qml
dcc-network/qml/PageDetails.qml
dcc-network/qml/PageHotspot.qml
dcc-network/qml/PageSettings.qml
dcc-network/qml/PageVPNSettings.qml
debian/changelog

Standardize IconLabel writing
bump version to 2.0.38
pms: Task-364175

fix: Standardize IconLabel writing

---

dcc-network/qml/NetPasswordEdit.qml
dcc-network/qml/SectionPPPOE.qml
dcc-network/qml/SectionVPN.qml
dcc-network/qml/SystemProxyConfigItem.qml

Processing password unedited and not visible
pms: BUG-287123

fix: Processing password unedited and not visible

---

dcc-network/qml/PageVPNSettings.qml

Modifying VPN configuration file without naming issue
pms: BUG-287091

fix: Modifying VPN configuration file without naming issue

---

dcc-network/qml/PageDSLSettings.qml
dcc-network/qml/PageSettings.qml
dcc-network/qml/PageSystemProxy.qml
dcc-network/qml/PageWirelessDevice.qml
dcc-network/qml/SectionDevice.qml
dcc-network/qml/SectionGeneric.qml
dcc-network/translations/network.ts
dcc-network/translations/network_az.ts
dcc-network/translations/network_bo.ts
dcc-network/translations/network_ca.ts
dcc-network/translations/network_es.ts
dcc-network/translations/network_fi.ts
dcc-network/translations/network_fr.ts
dcc-network/translations/network_hu.ts
dcc-network/translations/network_it.ts
dcc-network/translations/network_ja.ts
dcc-network/translations/network_ko.ts
dcc-network/translations/network_nb_NO.ts
dcc-network/translations/network_pl.ts
dcc-network/translations/network_pt_BR.ts
dcc-network/translations/network_ru.ts
dcc-network/translations/network_uk.ts
dcc-network/translations/network_zh_CN.ts
dcc-network/translations/network_zh_HK.ts
dcc-network/translations/network_zh_TW.ts
net-view/operation/netmanager.cpp
net-view/operation/private/netmanagerthreadprivate.cpp
net-view/operation/private/netmanagerthreadprivate.h

1. Modify the SSID location on the wireless network configuration page
2. Wireless network connection attempt to connect, wait to pull up the network panel and enter password
3. Handle VPN disconnection
4. System proxy URL with Required prompt
pms: BUG-286953
pms: BUG-291225
pms: BUG-287101

fix: Modify the SSID location on the wireless network configuration page

---

dcc-network/qml/network.qml
dcc-network/qml/networkMain.qml
dcc-network/translations/network.ts
dcc-network/translations/network_az.ts
dcc-network/translations/network_bo.ts
dcc-network/translations/network_ca.ts
dcc-network/translations/network_es.ts
dcc-network/translations/network_fi.ts
dcc-network/translations/network_fr.ts
dcc-network/translations/network_hu.ts
dcc-network/translations/network_it.ts
dcc-network/translations/network_ja.ts
dcc-network/translations/network_ko.ts
dcc-network/translations/network_nb_NO.ts
dcc-network/translations/network_pl.ts
dcc-network/translations/network_pt_BR.ts
dcc-network/translations/network_ru.ts
dcc-network/translations/network_uk.ts
dcc-network/translations/network_zh_CN.ts
dcc-network/translations/network_zh_HK.ts
dcc-network/translations/network_zh_TW.ts
net-view/operation/netmanager.cpp
net-view/operation/netmanager.h
net-view/operation/private/netmanagerthreadprivate.cpp
net-view/operation/private/netmanagerthreadprivate.h

网络加带参数的跳转
ShowPage参数
network?ssid=xxx       // 跳转到无线网络xxx的配置页面
network?page=wired     // 跳转到第一个有线网络页面
network?page=wireless  // 跳转到第一个无线网络页面
pms: TASK-361719

fix: Add network parameter jump function

---

dcc-network/qml/PageHotspot.qml

Modifying hotspot configuration errors resulted in inability to connect issues
Log:
pms: BUG-294499
pms: BUG-286589

fix: Modify hotspot configuration error

---

net-view/operation/private/netmanagerthreadprivate.cpp

Password configuration should not be saved without a password
pms: BUG-298371

fix: Password configuration should not be saved without a password

---

dss-network-plugin/network_module.cpp

iconButton's ownership is caller, it will access wild pointer
if it's released in 1ms.

fix: access wild pointer

---

debian/changelog

chore: bump version to 2.0.49 update changelog

---

network-service-plugin/accountnetwork/session/accountnetwork/activeaccoutnetwork.cpp
network-service-plugin/accountnetwork/session/accountnetwork/activeaccoutnetwork.h
network-service-plugin/system/networkinitialization.cpp
network-service-plugin/system/networkinitialization.h

QObject::connect: Unique connection requires the slot to be a pointer to a member function of a QObject subclass.
pms: BUG-307619

fix: Modifying network connection issue without automatic creation

---

debian/changelog

chore: bump version to 2.0.50 update changelog

---

network-service-plugin/accountnetwork/session/accountnetwork/activeaccoutnetwork.cpp
network-service-plugin/system/networkinitialization.cpp

Smart pointer causes multiple releases
pms: BUG-308701

fix: Modify network service crash issue
